packages:
  - "packages/*"
catalog:
  typescript: "^5.9.3"
catalogs:
  testing:
    vitest: "^4.0.16"
  effect:
    effect: "3.19.12"
    "@effect/platform": "0.94.1"
    "@effect/platform-bun": "0.86.0"
    "@effect/platform-browser": "0.73.0"
    "@effect/platform-node": "0.103.0"
    "@effect/rpc": "0.72.2"
    "@effect/experimental": "0.58.0"
    "@effect/language-service": "^0.64.1"
    "@effect/sql": "0.49.0"
    "@effect/sql-pg": "0.49.7"
    "@effect/sql-kysely": "0.45.0"
    "@effect/cluster": "0.56.1"
    "@effect/opentelemetry": "0.60.0"
    "@effect/workflow": "0.16.0"
    "@effect-atom/atom": "0.4.11"
    "@effect/ai": "0.33.2"
    "@effect/ai-openrouter": "0.8.0"
    "@effect/vitest": "0.27.0"
